name: learnconnectmyself
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.4
  flutter_riverpod: ^3.0.3
  image_picker: ^1.2.0
  http: ^1.6.0
  google_sign_in: ^5.4.0
  flutter_dotenv: ^6.0.0
  google_generative_ai: ^0.4.7
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Jersey
      fonts:
        - asset: assets/fonts/Jersey_10/Jersey10-Regular.ttf

  assets:
    - assets/images/Logo.png
    - assets/images/google1.png
    - assets/images/facebook.png
    - .env
